happy_list = [
"This moment matters more than you think.",
"You earned this, don’t downplay it.",
"Not every day feels like this—savor it.",
"You’re doing better than you realize.",
"This is your effort paying off.",
"Small wins still count as wins.",
"Let yourself feel proud for once.",
"You’re allowed to enjoy this fully.",
"You made this happen.",
"Keep going, you’re on the right track.",
"This is what progress looks like.",
"You didn’t get lucky—you showed up.",
"Moments like this build your future.",
"Don’t rush past happiness.",
"This feeling is yours, own it.",
"You’re growing, even if slowly.",
"This is proof that things can work out.",
"Keep this memory close.",
"You deserve this kind of day.",
"This is a glimpse of what’s possible.",
"You handled things well.",
"You’re becoming someone stronger.",
"This is just the beginning.",
"You’re more capable than before.",
"Celebrate, even if quietly.",
"You made the right call.",
"This version of you is better.",
"You’re building momentum.",
"This didn’t happen by accident.",
"You showed up when it mattered.",
"Let this motivate your next step.",
"You’re closer than you were yesterday.",
"This is a good sign.",
"Things are aligning for you.",
"You’re learning how to win.",
"This energy suits you.",
"Stay in this moment a bit longer.",
"You’ve come further than you think.",
"This matters more than it seems.",
"You’re doing something right.",
"Let yourself feel happy without guilt.",
"You’re allowed to shine.",
"This is your moment—take it.",
"Keep trusting your process.",
"You’re moving forward, clearly.",
"This is worth remembering.",
"You’ve earned a pause.",
"Things are getting better.",
"You’re becoming consistent.",
"This is a step up for you."
]

sad_list = [
"It’s okay to feel like this.",
"You don’t have to be strong right now.",
"This feeling won’t stay forever.",
"You’re not alone in this.",
"It hurts because it mattered.",
"You’re allowed to slow down.",
"Not every day needs progress.",
"You can take a break from everything.",
"It’s okay if today is heavy.",
"You don’t need all the answers.",
"Some days are just meant to be survived.",
"You’re doing your best, even now.",
"This doesn’t define you.",
"You’re still here, and that counts.",
"Healing isn’t linear.",
"You’re allowed to feel tired.",
"This weight won’t last forever.",
"You’re stronger than this moment.",
"It’s okay to sit with it.",
"You don’t need to rush recovery.",
"You’re not falling behind.",
"This is part of being human.",
"Even this will pass.",
"You don’t need to fix everything today.",
"You’re allowed to rest emotionally.",
"This feeling is valid.",
"You’re still moving, even slowly.",
"You’re not broken.",
"This pain has meaning.",
"You’re allowed to miss things.",
"You don’t have to explain yourself.",
"It’s okay to not feel okay.",
"You’re doing enough.",
"Even quiet days matter.",
"You’re holding on—and that’s something.",
"You don’t need to hide this.",
"This is not the end of your story.",
"You’re allowed to be gentle with yourself.",
"You don’t need to be productive right now.",
"You’re still growing, even here.",
"This won’t last forever.",
"You’re allowed to take space.",
"You matter, even on hard days.",
"You’re doing better than you think.",
"This feeling will soften.",
"You don’t have to go through this alone.",
"You’re still worthy.",
"This is just a chapter.",
"You’re allowed to feel everything.",
"You will get through this."
]

angry_list = [
"Your feelings make sense.",
"Something crossed your boundary.",
"You’re allowed to be upset.",
"Just don’t let it control you.",
"Take a moment before reacting.",
"Not everything deserves your energy.",
"You don’t need to explode to be heard.",
"Breathe before you respond.",
"You can choose how to handle this.",
"Anger is a signal, not a solution.",
"Something matters to you—that’s why.",
"Don’t let this define your actions.",
"You’re bigger than this moment.",
"Pause. You’ll think clearer.",
"You don’t have to prove anything.",
"This isn’t worth losing yourself over.",
"You’re in control here.",
"Channel it, don’t waste it.",
"Not every fight is worth it.",
"You can step back.",
"You don’t need to react instantly.",
"Let it pass through you.",
"This feeling will fade.",
"You’re allowed to cool down.",
"Keep your dignity intact.",
"Think long-term, not just now.",
"You don’t have to win this.",
"Choose peace where possible.",
"Your energy is valuable.",
"Don’t spend it here.",
"You can respond, not react.",
"You’re still in control.",
"Let logic catch up with emotion.",
"This isn’t the whole picture.",
"You don’t need to escalate.",
"Protect your peace.",
"You’re allowed to disengage.",
"Stay grounded.",
"This moment will pass.",
"You’re stronger than the impulse.",
"Don’t let this shrink you.",
"Keep your standards high.",
"Walk away if needed.",
"You don’t owe a reaction.",
"Stay calm—it’s power.",
"You’re bigger than this situation.",
"This doesn’t deserve your full attention.",
"Hold your composure.",
"You’ll think clearer soon.",
"Let it go, strategically."
]